package com.teknophase.chat.ui.constants

enum class CountryCodes(val emoji: String, val countryName: String, val code: String) {
    AFGHANISTAN("🇦🇫", "Afghanistan", "+93"),
    ALBANIA("🇦🇱", "Albania", "+355"),
    ALGERIA("🇩🇿", "Algeria", "+213"),
    ANDORRA("🇦🇩", "Andorra", "+376"),
    ANGOLA("🇦🇴", "Angola", "+244"),
    ANTIGUA_AND_BARBUDA("🇦🇬", "Antigua and Barbuda", "+1-268"),
    ARGENTINA("🇦🇷", "Argentina", "+54"),
    ARMENIA("🇦🇲", "Armenia", "+374"),
    AUSTRALIA("🇦🇺", "Australia", "+61"),
    AUSTRIA("🇦🇹", "Austria", "+43"),
    AZERBAIJAN("🇦🇿", "Azerbaijan", "+994"),

    BOSNIA_AND_HERZEGOVINA("🇧🇦", "Bosnia and Herzegovina", "+387"),
    BARBADOS("🇧🇧", "Barbados", "+1-246"),
    BANGLADESH("🇧🇩", "Bangladesh", "+880"),
    BELGIUM("🇧🇪", "Belgium", "+32"),
    BENIN("🇧🇯", "Benin", "+229"),
    BERMUDA("🇧🇲", "Bermuda", "+1-441"),
    BRUNEI("🇧🇳", "Brunei", "+673"),
    BOLIVIA("🇧🇦", "Bolivia", "+591"),
    BAHRAIN("🇧🇦", "Bahrain", "+973"),
    BURUNDI("🇧🇩", "Burundi", "+257"),
    BURKINA_FASO("🇧🇯", "Burkina Faso", "+226"),
    BELARUS("🇧🇾", "Belarus", "+375"),
    BELIZE("🇧🇿", "Belize", "+501"),
    BULGARIA("🇧🇬", "Bulgaria", "+359"),
    BOTSWANA("🇧🇼", "Botswana", "+267"),
    BRAZIL("🇧🇷", "Brazil", "+55"),
    BHUTAN("🇧🇹", "Bhutan", "+975"),

    CAMBODIA("🇰🇭", "Cambodia", "+855"),
    CAMEROON("🇨🇲", "Cameroon", "+237"),
    CANADA("🇨🇦", "Canada", "+1"),
    CAPE_VERDE("🇨🇻", "Cape Verde", "+238"),
    CENTRAL_AFRICAN_REPUBLIC("🇨🇫", "Central African Republic", "+236"),
    CHAD("🇹🇩", "Chad", "+235"),
    CHILE("🇨🇱", "Chile", "+56"),
    CHINA("🇨🇳", "China", "+86"),
    COLOMBIA("🇨🇴", "Colombia", "+57"),
    COMOROS("🇰🇲", "Comoros", "+269"),
    CONGO("🇨🇬", "Congo", "+242"),
    COSTA_RICA("🇨🇷", "Costa Rica", "+506"),
    CROATIA("🇭🇷", "Croatia", "+385"),
    CUBA("🇨🇺", "Cuba", "+53"),
    CYPRUS("🇨🇾", "Cyprus", "+357"),
    CZECH_REPUBLIC("🇨🇿", "Czech Republic", "+420"),

    DENMARK("🇩🇰", "Denmark", "+45"),
    DJIBOUTI("🇩🇯", "Djibouti", "+253"),
    DOMINICA("🇩🇲", "Dominica", "+1-767"),
    DOMINICAN_REPUBLIC("🇩🇴", "Dominican Republic", "+1-809"),

    ECUADOR("🇪🇨", "Ecuador", "+593"),
    EGYPT("🇪🇬", "Egypt", "+20"),
    EL_SALVADOR("🇸🇻", "El Salvador", "+503"),
    EQUATORIAL_GUINEA("🇬🇶", "Equatorial Guinea", "+240"),
    ERITREA("🇪🇷", "Eritrea", "+291"),
    ESTONIA("🇪🇪", "Estonia", "+372"),
    ESWATINI("🇸🇿", "Eswatini", "+268"),
    ETHIOPIA("🇪🇹", "Ethiopia", "+251"),

    FIJI("🇫🇯", "Fiji", "+679"),
    FINLAND("🇫🇮", "Finland", "+358"),
    FRANCE("🇫🇷", "France", "+33"),

    GABON("🇬🇦", "Gabon", "+241"),
    GAMBIA("🇬🇲", "Gambia", "+220"),
    GEORGIA("🇬🇪", "Georgia", "+995"),
    GERMANY("🇩🇪", "Germany", "+49"),
    GHANA("🇬🇭", "Ghana", "+233"),
    GREECE("🇬🇷", "Greece", "+30"),
    GRENADA("🇬🇩", "Grenada", "+1-473"),
    GUATEMALA("🇬🇹", "Guatemala", "+502"),
    GUINEA("🇬🇳", "Guinea", "+224"),
    GUINEA_BISSAU("🇬🇼", "Guinea-Bissau", "+245"),
    GUYANA("🇬🇾", "Guyana", "+592"),

    HAITI("🇭🇹", "Haiti", "+509"),
    HONDURAS("🇭🇳", "Honduras", "+504"),
    HUNGARY("🇭🇺", "Hungary", "+36"),

    ICELAND("🇮🇸", "Iceland", "+354"),
    INDIA("🇮🇳", "India", "+91"),
    INDONESIA("🇮🇩", "Indonesia", "+62"),
    IRAN("🇮🇷", "Iran", "+98"),
    IRAQ("🇮🇶", "Iraq", "+964"),
    IRELAND("🇮🇪", "Ireland", "+353"),
    ISRAEL("🇮🇱", "Israel", "+972"),
    ITALY("🇮🇹", "Italy", "+39"),

    JAMAICA("🇯🇲", "Jamaica", "+1-876"),
    JAPAN("🇯🇵", "Japan", "+81"),
    JORDAN("🇯🇴", "Jordan", "+962"),

    KAZAKHSTAN("🇰🇿", "Kazakhstan", "+7"),
    KENYA("🇰🇪", "Kenya", "+254"),
    KIRIBATI("🇰🇮", "Kiribati", "+686"),
    KUWAIT("🇰🇼", "Kuwait", "+965"),
    KYRGYZSTAN("🇰🇬", "Kyrgyzstan", "+996"),

    LAOS("🇱🇦", "Laos", "+856"),
    LATVIA("🇱🇻", "Latvia", "+371"),
    LEBANON("🇱🇧", "Lebanon", "+961"),
    LESOTHO("🇱🇸", "Lesotho", "+266"),
    LIBERIA("🇱🇷", "Liberia", "+231"),
    LIBYA("🇱🇾", "Libya", "+218"),
    LIECHTENSTEIN("🇱🇮", "Liechtenstein", "+423"),
    LITHUANIA("🇱🇹", "Lithuania", "+370"),
    LUXEMBOURG("🇱🇺", "Luxembourg", "+352"),

    MADAGASCAR("🇲🇬", "Madagascar", "+261"),
    MALAWI("🇲🇼", "Malawi", "+265"),
    MALAYSIA("🇲🇾", "Malaysia", "+60"),
    MALDIVES("🇲🇻", "Maldives", "+960"),
    MALI("🇲🇱", "Mali", "+223"),
    MALTA("🇲🇹", "Malta", "+356"),
    MARSHALL_ISLANDS("🇲🇭", "Marshall Islands", "+692"),
    MAURITANIA("🇲🇷", "Mauritania", "+222"),
    MAURITIUS("🇲🇺", "Mauritius", "+230"),
    MEXICO("🇲🇽", "Mexico", "+52"),
    MICRONESIA("🇫🇲", "Micronesia", "+691"),
    MOLDOVA("🇲🇩", "Moldova", "+373"),
    MONACO("🇲🇨", "Monaco", "+377"),
    MONGOLIA("🇲🇳", "Mongolia", "+976"),
    MONTENEGRO("🇲🇪", "Montenegro", "+382"),
    MOROCCO("🇲🇦", "Morocco", "+212"),
    MOZAMBIQUE("🇲🇿", "Mozambique", "+258"),
    MYANMAR("🇲🇲", "Myanmar", "+95"),

    NAMIBIA("🇳🇦", "Namibia", "+264"),
    NAURU("🇳🇷", "Nauru", "+674"),
    NEPAL("🇳🇵", "Nepal", "+977"),
    NETHERLANDS("🇳🇱", "Netherlands", "+31"),
    NEW_ZEALAND("🇳🇿", "New Zealand", "+64"),
    NICARAGUA("🇳🇮", "Nicaragua", "+505"),
    NIGER("🇳🇪", "Niger", "+227"),
    NIGERIA("🇳🇬", "Nigeria", "+234"),
    NORTH_KOREA("🇰🇵", "North Korea", "+850"),
    NORTH_MACEDONIA("🇲🇰", "North Macedonia", "+389"),
    NORWAY("🇳🇴", "Norway", "+47"),

    OMAN("🇴🇲", "Oman", "+968"),

    PAKISTAN("🇵🇰", "Pakistan", "+92"),
    PALAU("🇵🇼", "Palau", "+680"),
    PALESTINE("🇵🇸", "Palestine", "+970"),
    PANAMA("🇵🇦", "Panama", "+507"),
    PAPUA_NEW_GUINEA("🇵🇬", "Papua New Guinea", "+675"),
    PARAGUAY("🇵🇾", "Paraguay", "+595"),
    PERU("🇵🇪", "Peru", "+51"),
    PHILIPPINES("🇵🇭", "Philippines", "+63"),
    POLAND("🇵🇱", "Poland", "+48"),
    PORTUGAL("🇵🇹", "Portugal", "+351"),

    QATAR("🇶🇦", "Qatar", "+974"),

    ROMANIA("🇷🇴", "Romania", "+40"),
    RUSSIA("🇷🇺", "Russia", "+7"),
    RWANDA("🇷🇼", "Rwanda", "+250"),

    SAINT_KITTS_AND_NEVIS("🇰🇳", "Saint Kitts and Nevis", "+1-869"),
    SAINT_LUCIA("🇱🇨", "Saint Lucia", "+1-758"),
    SAINT_VINCENT_AND_THE_GRENADINES("🇻🇨", "Saint Vincent and the Grenadines", "+1-784"),
    SAMOA("🇼🇸", "Samoa", "+685"),
    SAN_MARINO("🇸🇲", "San Marino", "+378"),
    SAO_TOME_AND_PRINCIPE("🇸🇹", "Sao Tome and Principe", "+239"),
    SAUDI_ARABIA("🇸🇦", "Saudi Arabia", "+966"),
    SENEGAL("🇸🇳", "Senegal", "+221"),
    SERBIA("🇷🇸", "Serbia", "+381"),
    SEYCHELLES("🇸🇨", "Seychelles", "+248"),
    SIERRA_LEONE("🇸🇱", "Sierra Leone", "+232"),
    SINGAPORE("🇸🇬", "Singapore", "+65"),
    SLOVAKIA("🇸🇰", "Slovakia", "+421"),
    SLOVENIA("🇸🇮", "Slovenia", "+386"),
    SOLOMON_ISLANDS("🇸🇧", "Solomon Islands", "+677"),
    SOMALIA("🇸🇴", "Somalia", "+252"),
    SOUTH_AFRICA("🇿🇦", "South Africa", "+27"),
    SOUTH_KOREA("🇰🇷", "South Korea", "+82"),
    SOUTH_SUDAN("🇸🇸", "South Sudan", "+211"),
    SPAIN("🇪🇸", "Spain", "+34"),
    SRI_LANKA("🇱🇰", "Sri Lanka", "+94"),
    SUDAN("🇸🇩", "Sudan", "+249"),
    SURINAME("🇸🇷", "Suriname", "+597"),
    SWEDEN("🇸🇪", "Sweden", "+46"),
    SWITZERLAND("🇨🇭", "Switzerland", "+41"),
    SYRIA("🇸🇾", "Syria", "+963"),

    TAIWAN("🇹🇼", "Taiwan", "+886"),
    TAJIKISTAN("🇹🇯", "Tajikistan", "+992"),
    TANZANIA("🇹🇿", "Tanzania", "+255"),
    THAILAND("🇹🇭", "Thailand", "+66"),
    TIMOR_LESTE("🇹🇱", "Timor-Leste", "+670"),
    TOGO("🇹🇬", "Togo", "+228"),
    TONGA("🇹🇴", "Tonga", "+676"),
    TRINIDAD_AND_TOBAGO("🇹🇹", "Trinidad and Tobago", "+1-868"),
    TUNISIA("🇹🇳", "Tunisia", "+216"),
    TURKEY("🇹🇷", "Turkey", "+90"),
    TURKMENISTAN("🇹🇲", "Turkmenistan", "+993"),
    TUVALU("🇹🇻", "Tuvalu", "+688"),

    UGANDA("🇺🇬", "Uganda", "+256"),
    UKRAINE("🇺🇦", "Ukraine", "+380"),
    UNITED_ARAB_EMIRATES("🇦🇪", "United Arab Emirates", "+971"),
    UNITED_KINGDOM("🇬🇧", "United Kingdom", "+44"),
    UNITED_STATES("🇺🇸", "United States", "+1"),
    URUGUAY("🇺🇾", "Uruguay", "+598"),
    UZBEKISTAN("🇺🇿", "Uzbekistan", "+998"),

    VANUATU("🇻🇺", "Vanuatu", "+678"),
    VATICAN_CITY("🇻🇦", "Vatican City", "+379"),
    VENEZUELA("🇻🇪", "Venezuela", "+58"),
    VIETNAM("🇻🇳", "Vietnam", "+84"),

    WALLIS_AND_FUTUNA("🇼🇫", "Wallis and Futuna", "+681"),
    WESTERN_SAHARA("🇪🇭", "Western Sahara", "+212"),

    YEMEN("🇾🇪", "Yemen", "+967"),

    ZAMBIA("🇿🇲", "Zambia", "+260"),
    ZIMBABWE("🇿🇼", "Zimbabwe", "+263")
}